Vagrant.configure("2") do |config|
    config.vm.provider = "virtualbox"
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.network "private_network", ip: "55.55.55.150"
    config.vm.synced_folder ".", "/home/vagrant/shared/"
    config.vm.provision "shell", inline: <<-SHELL    
        sudo apt-get update -y
    SHELL
end